// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "wright.brett@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contactinfo": {
            "get": {
                "description": "Get the contact information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Gets the contact information",
                "responses": {
                    "200": {}
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Updates contact information",
                "responses": {
                    "200": {}
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Creates contact information",
                "parameters": [
                    {
                        "description": "Personal Contact Information",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ContactInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "contact"
                ],
                "summary": "Deletes contact information",
                "responses": {
                    "200": {}
                }
            }
        },
        "/education": {
            "get": {
                "description": "Gets all Educational information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Education"
                ],
                "summary": "Gets all Educational information",
                "responses": {
                    "200": {}
                }
            },
            "post": {
                "description": "Get the contact information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Education"
                ],
                "summary": "Creates Education information",
                "responses": {
                    "200": {}
                }
            }
        },
        "/education/{id}": {
            "get": {
                "description": "Get the contact information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Education"
                ],
                "summary": "reads Education information",
                "responses": {
                    "200": {},
                    "404": {
                        "description": "education id not found"
                    }
                }
            },
            "put": {
                "description": "Updates the education information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Education"
                ],
                "summary": "updates Educational information",
                "responses": {
                    "200": {},
                    "404": {}
                }
            },
            "delete": {
                "description": "deletes the eduation information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Education"
                ],
                "summary": "deletes education information",
                "responses": {
                    "200": {},
                    "404": {}
                }
            }
        },
        "/experience": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experience"
                ],
                "summary": "Get all experience information",
                "responses": {
                    "200": {}
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experience"
                ],
                "summary": "Creates Experience information",
                "responses": {
                    "200": {}
                }
            }
        },
        "/experience/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experience"
                ],
                "summary": "Reads Experience information",
                "responses": {
                    "200": {}
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experience"
                ],
                "summary": "Updates Experience information",
                "responses": {
                    "200": {}
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experience"
                ],
                "summary": "Deletes Experience information",
                "responses": {
                    "200": {}
                }
            }
        },
        "/language": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "Creates Language information",
                "responses": {
                    "200": {}
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "Creates Language information",
                "responses": {
                    "200": {}
                }
            }
        },
        "/language/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "Creates Language information",
                "responses": {
                    "200": {}
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "Creates Language information",
                "responses": {
                    "200": {}
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "Creates Language information",
                "responses": {
                    "200": {}
                }
            }
        },
        "/resume": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get the entire resume information",
                "responses": {
                    "200": {}
                }
            }
        }
    },
    "definitions": {
        "models.ContactInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "github": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "linkedin": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "postcode": {
                    "type": "integer"
                },
                "town": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Resume API",
	Description: "REST API for my resume",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
